### ISSUE TITLE
Big error on joining and leaving the Server Quests 2.1.2

### ISSUE THREAD

**Issue by SimbaZockt** [FlyingPikachu/Quests#1]
http://pastebin.com/DhHAiaiP

**Comment by Colossoss** [comment]
I have the same Error with.
Spigot 1.8 build 302
Quests 2.1.2
Citizens-2.0.14-SNAPSHOT#1206
Vault 1.5.2

**Comment by FlyingPikachu** [comment]
My mistake. This is because the plugin is (like it should) trying to read data from the 'quester-blacklist' node in quests.yml. However. your config probably looks like:

quester-blacklist:
- UUID
- somePrefix*
- '*someSuffix'
- '*someRegex*'

The plugin gets confused when it tries to interpret "UUID" as an actual UUID. Either delete the list items or change them all to "UUID" & update to Quests 2.1.3.

Thanks for reporting this issue! :)
