### ISSUE TITLE
Stage goal Kill xxx mobs having combat tag issue?

### ISSUE THREAD

**Issue by Leescar** [FlyingPikachu/Quests#10]
When I have a quest setup to kill 5 Zombies the count will not increase when you kill with the following methods:

--Bow an arrow ranged shot
--Potion of harm(I & II) on living mobs
--Potion of healing(I & II) on undead mobs
--Punching a mob which results in a mobs fall death

The following methods are the ones that work and increase goal:
--Killing with sword
--Punching to death with bare fist
--Punching to death with item in hand.

No errors in console

**Comment by NathanWolf** [comment]
I've run into this, too- looking in the code I can see that

1) I think the "damager" check for projectiles is using the wrong entity- it is looking at the entity that got damaged and checking if it is a player/quester

2) Potion damage just isn't handled at all. It has to be handled in the same way as projectiles- checking for a splash potion as the damager, and then getting the "shooter" of the potion. I think.

#2 is also important for me because I use splash potion damage as my custom "magic" direct damage.

I will see if I can make a PR to fix these issues!

Well... the "pushed to a fall death" thing I'm not so sure about, honestly. I'll do some testing there and see if there's any way the last damage cause relates back to the player- you'd think so since it seems to work with death messages, same as when they run into fire or lava after you hit them.
