### ISSUE TITLE
Give written books and potions as rewards

### ISSUE THREAD

**Issue by AIphaDragon** [FlyingPikachu/Quests#107]
Version: 2.9.4

The issue is, that in our quest a player needs to receive a written book with some text in it. So, when he receives the book, there are no text in it except *Invalid book tag*. We want to give a book as a reward of finishing quest.
The same situation with a 3.0.0 version

Pastebin of quest: https://pastebin.com/MePkdUu7

We are looking forward to your answer

**Comment by LinearBotSystems** [comment]
It is the same with potions currently there is no way to make them a reward directly because of the missing meta data. I did make a crude workaround with the command option since I have no data there who is the player or I have no idea what the wildcard is for player I'm forced to use nearest -p ? 

Somebody might do this someday it is mostly just an assiduity task add 2 new menus and add extra data structures + adding code to the load and save function. I just have to do a lot atm and I also wait for the plugin to become more stable before I start doing this also Minecraft 1.13 will change some  data structures with the potential to break some stuff again.  AH I forgot in 1.13 there will be also custom recipes makes 3 options...

**Comment by FlyingPikachu** [comment]
@AlphaDragon The ability to give rewards with metadata (books and potions) is not included with Quests at this time. As @LinearBotSystems noted, MC 1.13 will change how metadata is structured, so I'm holding off on this feature until then (otherwise it'll be more work if it breaks).

**Comment by LinearBotSystems** [comment]
You could maybe really add a bit of code to the command option where a substring like "*questplayer" will be replayed by the current quester's player name when getting the rewards ?

This should be only 2-3 lines of code

**Comment by SXRWahrheit** [comment]
Pretty sure you can do this with Denizen in the meantime

**Comment by FlyingPikachu** [comment]
Latest commit adds support for both Written Books and Potions. If you experience a issue while testing, please open a new ticket. Thanks!
