### ISSUE TITLE
Letter Ñ

### ISSUE THREAD

**Issue by sahudon** [FlyingPikachu/Quests#116]
(__Required__) What is your Quests version / build number Quests-3.0.0-Naomi

(__Required__) Spanish letter Ñ in the quests appear like á+- (pic http://prntscr.com/ge3se8) how solve this?

**Comment by FlyingPikachu** [comment]
This is likely a limitation of the YAML format, but I'll take a look!

Please post the quest from quests.yml for testing.

**Comment by sahudon** [comment]
https://pastebin.com/mwxBSNPj take

**Comment by FlyingPikachu** [comment]
Instead of the format being at fault, it's actually the way in which Bukkit/Spigot loads the file. This can be easily fixed and I intend to do so in a future build.

Personal note - https://github.com/FlyingPikachu/SimpleCarts/blob/master/SimpleCarts/src/me/happypikachu/SimpleCarts/util/Localization.java#L55

**Comment by sahudon** [comment]
Does that mean that if the player has the language in Spanish will not appear the items for the mission in English?
