### ISSUE TITLE
TRANSLATE FILE REQUEST

### ISSUE THREAD

**Issue by KingMyrrdin** [FlyingPikachu/Quests#120]
any possibility for more options in translate file?
for example color codes like &e or <red> in message. 
Or option for delete message completely, because now when i wrote like this questObjectivesTitle: "" it shows clear line in chat. maybe make option for example when i wrote like this questObjectivesTitle: "null" its delete message.

Realy need that, because  now all these colors and apportionment (or Positioning I dont know how to say it) look realy messy and i need to make it diferent for some reasons.

sorry for english, best regards

**Comment by FlyingPikachu** [comment]
Removing the "clear line in chat" would not an easy feat as far as I can tell due to the way Quests currently reads from the language file. Although I understand this is a popular request, this enhancement is best left to someone that wants it bad enough to submit a PR themselves.

As for color formatting, this is already possible - https://github.com/FlyingPikachu/Quests/wiki/Translations
