### ISSUE TITLE
PlayerMoveEvent console errors

### ISSUE THREAD

**Issue by whoshenry** [FlyingPikachu/Quests#126]
I am getting these errors in the console a lot - http://pastebin.com/457ns0Q5

**Comment by whoshenry** [comment]
I think this has something to do with Citizens acting up sometimes actually. Maybe on a reload of one of the plugins?

**Comment by bscal** [comment]
I have been getting the same errors. Reloading does not fix the problem for me have you figured out a way to fix this?

**Comment by bscal** [comment]
Ok well this fixed mine and I am no longer getting any errors in the console. I am running the latest version of spigot citizens and quests. I found out that the latest citizens build may be causing it because its for spigot 1.8.6 not 1.8.7 so go into the citizens config and put check-minecraft-version: from true to false. This is what I did and it worked out for me.

**Comment by whoshenry** [comment]
Still getting spammed with this error, doing your method above didn't fix it.
