### ISSUE TITLE
Command rewards: Execute commands from console.

### ISSUE THREAD

**Issue by Deathinflames** [FlyingPikachu/Quests#141]
Hello,

First, i just wanted to tell you how much we appreciate that you've taken over development of this project. We've used quite a few different quest plugins, and we were deeply saddened when Blackvein went MIA as this plugin has always been our goto for a quest system.

As we progress through the quest creation process, we have not run into a single issue with version 2.5.1, except when we try to use command rewards. We've created some custom commands via another plugin that we would like to have executed as rewards via Quests, however upon execution we receive unknown command. When attempting the command by a live player in-game however, they work just fine.

If i understand correctly, the commands that Quests is able to execute are ones that have been registered in another plugin's plugin.yml. I understand that this may just be a code limitation issue that cannot be resolved with how we are attempting to execute our custom commands, but a workaround may be to execute these commands on the player via the console. Our question is, Is there a way currently to accomplish this that we are not aware of, or is this a feature that will need to be added?

Thank you for your time.

Regards,
Death

**Comment by FlyingPikachu** [comment]
As you can see from the line of code below, Quests executes the command via console. With that in mind, it is logical to assume your command is not accessible via the console. In other words, the issue is likely with how your command is set up.

https://github.com/FlyingPikachu/Quests/blob/163de45dea6120bf359e495ee45d72593e6666f9/src/main/java/me/blackvein/quests/Quest.java#L318
