### ISSUE TITLE
Storm Event

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#144]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Noami
(__Required__) Please describe the problem and how to replicate it. Any console errors?
Try to make a new event. Try to add storm. Add world. After that i cant set the duration and get a NULL in chat
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
no

**Comment by FlyingPikachu** [comment]
The "NULL" was caused by Quests looking in the Lang file for "eventEditorEnterStormDuration" when the correct tag is "eventEditorEnterDuration". This has been fixed internally and no action is needed on your part (other than to update to the new dev build).

However, there was a secondary issue where both Storm and Thunder accept milliseconds for their duration. This should have been done away with ages ago as we use seconds for all time input now. The latest commit ought to correct this. You may want to update any Storm/Thunder events you have saved.
