### ISSUE TITLE
Events in CustomObjectives suddenly stop being listened for?

### ISSUE THREAD

**Issue by xikage** [FlyingPikachu/Quests#160]
Hi HappyPikachu,

I'm the author of MythicMobs, along with the MM Quests module. I've been getting reports of (and experiencing) instances where the module will rarely just suddenly stop working until a /questadmin reload is done. I've done some debugging on my end and it appears the death event just stops being listened for. I haven't been able to figure out why it's happening, though.

Here's the code for the module in-case you want to have a look, it's nothing special:
http://hastebin.com/rekahozuho.avrasm

If it's something on my end could you let me know if I'm doing something incorrectly? Definitely want to get this fixed up.

Thanks!

**Comment by FlyingPikachu** [comment]
Your code looks fine to me. It's likely related to some of the issues Quests has been experiencing lately. Development is slow as life throws me around, so there may not be an immediate fix. Still, thank you for bringing this to my attention! :)

**Comment by FlyingPikachu** [comment]
See #164 for a likely cause

**Comment by Neoblade298** [comment]
Is there any way I can help debug this? My server depends on mythicmobs as well, and although I can get around this, it'll require a bit of work making mobs drop unique items and editing the quests to take the items.

If I can help debug, could you point out how I'd get started? For example, are we looking for an error when players disconnect? A null pointer in quest data? Do we have information to start with (Like for example, this error only happens when the player has the mythicmobs quest module quest)?

**Comment by xikage** [comment]
I am not sure #164 is related. I have never personally seen that error pop up when a player quits.

**Comment by FlyingPikachu** [comment]
Finally fixed in #231 (Quests 2.5.3)
