### ISSUE TITLE
Can't save events

### ISSUE THREAD

**Issue by Worlfy** [FlyingPikachu/Quests#189]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.1.6

(__Required__) Please describe the problem and how to replicate it. Any console errors?
When I try to save an event, it just gives me an error and does nothing until I say "No"

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Not what it's related to

**Comment by christophe6** [comment]
I have the same problem! This problem does occur too when reloading with /questadmin reload.
This is my error log for that command:
`25.12 21:39:53 [Server] INFO Christophe6 issued server command: /questadmin reload
25.12 21:40:00 [Server] ERROR null
25.12 21:40:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.1.2-b192
25.12 21:40:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
25.12 21:40:00 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [Spigot.jar:git-Spigot-3fb9445-6e3cec8]
25.12 21:40:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
25.12 21:40:00 [Server] INFO Caused by: java.lang.OutOfMemoryError: Java heap space
25.12 21:40:00 [Server] INFO at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_151]
25.12 21:40:00 [Server] INFO at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[?:1.8.0_151]
25.12 21:40:00 [Server] INFO at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448) ~[?:1.8.0_151]
25.12 21:40:00 [Server] INFO at java.lang.StringBuilder.append(StringBuilder.java:136) ~[?:1.8.0_151]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Quests.getLocation(Quests.java:3397) ~[?:?]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Event.loadEvent(Event.java:556) ~[?:?]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Quests.loadEvents(Quests.java:3211) ~[?:?]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Quests.reloadQuests(Quests.java:1883) ~[?:?]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Quests.adminReload(Quests.java:626) ~[?:?]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:581) ~[?:?]
25.12 21:40:00 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:570) ~[?:?]
25.12 21:40:06 [Multicraft] Skipped 3 lines due to rate limit (30/s)`

**Comment by FlyingPikachu** [comment]
@Worlfy This does not happen for me when creating a Give Items event in Quests 3.1.6 (see image below), nor do I get any errors during or after a reload. Perhaps it's only for specific events? Which type of event were you trying to create?

![screenshot](https://i.imgur.com/DkrOJBZ.png)

@christophe6 That error is unrelated and caused by insufficient memory in your server environment (not enough RAM allocated). I also highly recommend updating to Quests 3.1.6.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. Please try a newer build of Quests and, if the issue presists, create a new ticket with the requested information.
