### ISSUE TITLE
My server is crashing when i save Quest in /Quests editor.

### ISSUE THREAD

**Issue by ItSBufferBG** [FlyingPikachu/Quests#194]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests Version: 3.1.6

(__Required__) Please describe the problem and how to replicate it. Any console errors?
When i start editing a quest and finish my editing i go save and its asking me yes or no. I press 1-which is yes and i get kicked out of the server.
Console Errors:  https://pastebin.com/cDeFd9kP

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/ZbBaSejy

**Comment by ItSBufferBG** [comment]
So i try so many things changing versions and so on and its still happening

**Comment by FlyingPikachu** [comment]
What sort of quest are you trying to create? Looks like something with an enchantment?

**Comment by ItSBufferBG** [comment]
Amm yes im giving armor with protection 2 when the  quest starts!

**Comment by ItSBufferBG** [comment]
I fix it.  I removed the giving items in /questa events command.  There is a option to give them syart items and its ok.  But there is another bug.  Where in rewards i get item called (null)  and if i am i quests editor i cant save or exit the quests editor

**Comment by FlyingPikachu** [comment]
I was able to create a "Give items" event with a Sharpness III Diamond Sword and take the quest via NPC without any issues. This was on a dev build, however (http://ci.ac3-servers.eu/job/Quests/223/). Although you've decided to drop the issue, you're welcome to try that build and post the new error if you ever feel like having me take a second look.

As for item rewards (through /quests editor), I was able to use the same Diamond Sword and that's what I got back as well after completing the quest. No (null) items. Perhaps you could share your updated quest from quests.yml in a _new_ issue (since this is a separate bug) and I'll take a look? :)
