### ISSUE TITLE
Recommendation For Quitting Quests

### ISSUE THREAD

**Issue by johnsoncui02** [FlyingPikachu/Quests#225]
Just a quick recommendation for a easier way to quit quests.
/quests quit (questname) seems a bit of work

If possible, try to adjust it to abandon all quests or the very previous quest. First option is much easier to take care of. Unless there are servers that allow people to accept 20 quests at a time which would defeat the purpose of this plugin pretty much.

If possible, shorten to this to abandon quests. This would also be a addon to chestcommands to make features extra easy to configure.
/quests quit or /qq or /quit

Before I end this thread, I'd just like to thank you for developing this plugin and made it free for everyone to use. This as brought alot of features to my server and i am thankful for that.

**Comment by FlyingPikachu** [comment]
It’s possible to take 2+ quests at a time if desired, so I’m afraid it would be detrimental to force players to quit ALL quests rather than specific ones. If it helps, I believe you don’t have to type the entire quest name - only the first few characters. At least, that’s how it works in the Quest Editor.

Thanks for the words of encouragement!
