### ISSUE TITLE
Feature Modification Request: Redo Delay

### ISSUE THREAD

**Issue by Grasty** [FlyingPikachu/Quests#23]
Quests already supports repeatable quests, but the way it is implemented to be honest ... kinda sucks. The way it works now, you can set a redo delay on a quest which will allow you to repeat the quest after that delay has finished, but the delay is in milliseconds. So I wanted to do a daily quest, one that could be repeated every 24 hours, so i did the math to figure out how many milliseconds are in 24 hours (86,400,000), but when i put that into the redo delay, it drops down to 1 hour, 46 minutes, 39 Seconds (or something arbitrary like that). I assume that this means that the redo delay has a cap that you cannot pass. This makes it impossible for me to do daily and weekly quests.

So I would like it very much if you could modify the redo delay to accept values such as 30m (for 30 minutes), 1h (for 1 hour), 1d (for 1 day), 1w (for 1 week)

If it is hard to add these values, I would be ok with changing the redo delay to be in minutes instead of milliseconds. I have no problem doing the math to figure out how many minutes in a day or a week, but milliseconds is a bit ridiculous. Or i would be happy with just minutes, hours, and days, or just minutes and hours.

This is by far the best Quests plugin out there, and this is the biggest (if not the only) thing that holds me back from using this plugin to its full extent.

That all being said, I think i have a fancy way of working around this using zpermissions, but i would highly prefer a redo delay in Quests that is actually useful.

**Comment by Formula350** [comment]
I agree, this would be far easier for anyone to use for delays. That, or at the very least, change it to Minutes instead of Milliseconds.

In regards to delays, seems something did change a bit between 2.0 and when Pikachu took over. A few of our quests that we set a "delay" on that would result in many years before ticking out (were unable to find a way to make them "never" able to be redone, but this was back in v1.x days of of Quests). Well despite having the delay set to something like:  999999999999  players are able to redo them immediately :\

If no "Redo-delay:" is set (totally absent, in the quests.yml) does that make it one-time-only?

Thanks!

**Comment by Grasty** [comment]
I believe that is correct, if you do not include a Redo Delay then it cannot be done again ever.

**Comment by FlyingPikachu** [comment]
I believe this is because Quests was loading the redo-delay value as an Integer instead of a Long. Please try dev build 58 and see if that works before we continue.

http://ci.ac3-servers.eu/job/Quests/58/

**Comment by Grasty** [comment]
It lets me do longer Redo Delays now, I was able to do 604,800,000 for 7 Days and 86,400,000 for 1 Day and it accepted it.

Thanks!

**Comment by FlyingPikachu** [comment]
Great! Now that that's resolved, should the redo-delay be in seconds or minutes? Or should I just leave it at milliseconds?

**Comment by Grasty** [comment]
It would probably be better to do minutes as opposed to milliseconds and probably easier to use ... That being said, im satisfied with the milliseconds working ... I can work with that. 

But it would be cool if it was in minutes.

**Comment by SimbaZockt** [comment]
or 1m 1h 10s 1d or something like you said in the first post.

**Comment by FlyingPikachu** [comment]
Included in dev build 60.

Opted to use seconds just in-case there's any time lords out there. Also I decided not do 1m 1h etc. because Quests uses milliseconds in various places internally so it was much easier to say "seconds times 1000" than a whole conversion process (aka I was lazy). Anyway, users will need to manually convert their config values from millis -> seconds and update their lang file(s). Thanks!

**Comment by Grasty** [comment]
I can live with that, thanks.
