### ISSUE TITLE
How can i make more quests in 1 quest?

### ISSUE THREAD

**Issue by Rowz** [FlyingPikachu/Quests#255]
Build number: 3.2.2

I want to make more quests in 1 quest. I cant find a tutorial about that. I want to make a tutorial that a npc is searching his glasses and you will go to an npc named "ron" He will gives you the glasses and you go bring it back to the NPC.

**Comment by FlyingPikachu** [comment]
A question like this is better asked on the Spigot discussion forum. However, I believe you will want to use the _/quests editor_ to add a Stage which includes a Deliver Item objective. You will need Citizens installed to use NPCs.

**Comment by Midnight9746** [comment]
Quest:

You talk to npc

npc: I can't find my glasses will you help me?

Stages:

1) Reach locations (too help look)

2) talk to ron

3) return back to the first npc

The thing is, that once you finish the quest, you get the rewards, but if you do the quest similar to what's above, you can pretend to give the player the glasses, but really you're completing the 'stage' which will then allow you to return to the first npc as if you got the glasses.

Doing the deliver item objective is assuming you already have the glasses, which you won't if it's supposed to be from the same quest. What you could do is have something near ron that gives you the glasses like a command block or using npc commands plugin, then set the give item since you 'got' them from ron.

Other than that, you're left with pretending you got the glasses

**Comment by FlyingPikachu** [comment]
A good answer by @Midnight9746, thanks! Hopefully this is sufficient. Otherwise, check out the discussion thread on Spigot.
