### ISSUE TITLE
Issue with Enchantments

### ISSUE THREAD

**Issue by Ugikie** [FlyingPikachu/Quests#26]
Having an issue with Enchantments where when you add an enchantment objective and first of all that menu is super confusing, looks like two different lists mashed together...and when I chose 'Fire Protection' it instantly broke the plugin and the quest was missing from the list upon re-entering the editor.

Seems like a similar issue with the mobs where the spaces aren't supported in the enchantment name and have to be changed probably to underscores.

Thanks in advance for all the support! :)

Heres a pic of the weird list...tried 'fireprotection' , 'fire_protection' , and 'fire protection' none of which work..

![](https://images-ext-1.discordapp.net/external/IMm4u2XGT2xbBQ-sl9Lls3BA_YtvSbX-iiKm7GE_NaA/https/i.gyazo.com/9f6d15a852661a3f8e9ec5a6b23fe28a.png)

**Comment by FlyingPikachu** [comment]
This is caused by the enchantment names not being present in your language file (en.yml by default), which is noted in the console when triggering this prompt. However, the names should've been added when these enchantments were introduced to Minecraft. I will correct this as well as improve the look of how missing names appear in this prompt.

@Ugikie Download the latest dev build shortly after this issue closes, or add the names to your language file manually to fix the problem. Thanks!
