### ISSUE TITLE
kill mob stage issue

### ISSUE THREAD

**Issue by joshthegrate** [FlyingPikachu/Quests#27]
when i make the quest in game it saves the mob names of PigZombie and MagmaCube as Pig Zombie and Magma Cube in the config. this breaks the quest if i go into the config and make a change anywhere unless i manually contract it back to a one word mob name.
how the game saves:
        '3':
          mobs-to-kill:
          - Ghast
          - Pig Zombie
          - Blaze
          - Magma Cube
          mob-amounts:
          - 20
          - 40
          - 20
          - 20
how i have to edit the file back:
        '3':
          mobs-to-kill:
          - Ghast
          - PigZombie
          - Blaze
          - MagmaCube
          mob-amounts:
          - 20
          - 40
          - 20
          - 20

**Comment by Formula350** [comment]
I had posted about this, and the fix (at least in stopping an error being output in the console), is to name them:
**Magma_Cube
Pig_Zombie**

Hope that helps!

**Comment by FlyingPikachu** [comment]
Cannot replicate this issue on the latest dev build. I think @Formula350 is correct in that it has already been resolved. Please give a recent dev build a try and if the problem is still there, post a new issue with the error you receive when Quests loads the file (and/or when saving if there is one).
