### ISSUE TITLE
Reload/Unfinished Quest

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#28]
I've noticed also sometimes when you are on a quest, if the plugin is reloaded, it removes the quest from you and you have to accept it from the npc again.  Not sure if this is meant to happen (I'm setting up my server and all the quests while testing everything before we open).
Edit for question: How do you reset a compass to to point towards the quest you're on? I know if I take another quest, after finishing the second one it will point back towards the first one. But if I finish the second one, log out for the night and come back to the first quest, it points towards my last bed spawn. I have to reload the plugin to reset the compass, if the quest is still on the stats list.

**Comment by FlyingPikachu** [comment]
Just tested the reload scenario and I was able to keep my progress through a reload. The compass thing sounds like a bug, but since that is off-topic and no errors, quest data, or other info has been provided for either issue, I'm closing this.

Feel free to open a new ticket _per issue_ with more information :)
