### ISSUE TITLE
Add Party System

### ISSUE THREAD

**Issue by Prowco** [FlyingPikachu/Quests#281]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
  Quests -3.2.4
(__Required__) Please describe the problem and how to replicate it. Any console errors?
I dont have any problem i just want to know if you can add a party sistem please? I mean if you have 3 party members and you complete a quest every member get the rewards, and add in requeriments party members minimum for quest if you put 2 you need another user for take that mission you know what i mean? and an option for party members pvp on/off Please? awsome resource love it.

**Comment by FlyingPikachu** [comment]
It should be noted that preliminary code for a party system has been present in the plugin since before I took it over from Blackvein. Nothing works, but here's hoping it will be completed someday! A few quick links to those bits:

Permissions: https://github.com/FlyingPikachu/Quests/blob/b4fe66f0366f7ace57a9dcfd370049425c36a62c/src/main/resources/plugin.yml#L110
Commands: https://github.com/FlyingPikachu/Quests/blob/a3e25b0ec00db40f9559971c1888abd416f09a46/src/main/java/me/blackvein/quests/Quests.java#L680
Variable: https://github.com/FlyingPikachu/Quests/blob/329875bd32f49efa51f9c83435acb81b1906eb8b/src/main/java/me/blackvein/quests/util/CK.java#L156

**Comment by FlyingPikachu** [comment]
Currently looking at integrating with [Parties](https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/). Even though the original author of Quests had planned to implement first-party support, I think it may be best to use a purpose-built dependency which can do it better. This is also not a highly requested feature to my knowledge.

**Comment by FlyingPikachu** [comment]
Added aforementioned support in http://ci.ac3-servers.eu/job/Quests/596/
