### ISSUE TITLE
After quest message

### ISSUE THREAD

**Issue by JustinSaenCity** [FlyingPikachu/Quests#288]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.2.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Is there a way that after finishing a quest, not seeing 'no more quests available', but a custom message for each NPC, I altready tried it with permissions, but you still need to select the quest, so that doesn't work.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
  custom5:
    name: To Warrington
    npc-giver-id: 48
    ask-message: '§2Wymark: §7Hey, are you awake? You are the last! Fast go to Warrington, it is the village behind the path. Good luck!'
    finish-message: '§2Ballista: §7Hey can I talk to you?'
    stages:
      ordered:
        '1':
          locations-to-reach:
          - world -400.0 74.0 275.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Warrington
    rewards:
      items:
      - name-EMERALD:amount-20
      quest-points: 1
      commands:
      - rpl admin getexp <player> 20

And what I want is somthing for a message after finishing the quest in here somewhere.

**Comment by FlyingPikachu** [comment]
You can replace the string in your /lang/**/strings.yml file, but it will be the same for every NPC. There are methods to send additional test, like the finish-message in Quest Editor and certain events in the Events Editor, but the "no more quests available" cannot be removed entirely.

**Comment by FlyingPikachu** [comment]
@JustinSaenCity Just occurred to me, you might want to take a look at this, which _might_ be able to accomplish what you're trying to do - https://github.com/FlyingPikachu/Quests/wiki/Translations#placeholderapi

**Comment by JustinSaenCity** [comment]
How would I do it with those placeholder, I am sorry, but don't really understand.

**Comment by FlyingPikachu** [comment]
@JustinSaenCity You'd have to look through their placeholders and see if there's any that will add the customization you're looking for - https://www.spigotmc.org/wiki/placeholderapi-placeholders/

**Comment by JustinSaenCity** [comment]
But I want custom messages. One for all quests appart.

**Comment by Midnight9746** [comment]
What they are trying to do is when you click an npc after a quest it says something different.

Example (When you finish all their quests):

John: "Woah! Slow down, there's nothing more for you to do!"

Sally: "Oh I'm sorry! I'm afraid I'm all out of quests for you."

Kate: "What do you want from me now?"

Rather them all saying "No more quests available"

I initially thought the lang config, but realized that won't work. Could npc command plugin override a player's right click? Only asking because then they could have that plugin say no more quests when right clicked and quests will ignore it. Assuming that the npc commands will only trigger when the player has a set permission. (Like when you finish the quest, reward the player with something like questname.complete) So that when the npc gets clicked it will know the player has permission to active the message rather than quests. But I'm not sure, could bug it out entirely where it says no permissions.

Maybe you can add something to the plugin to allow it per-quest, rather than a whole.

**Comment by JustinSaenCity** [comment]
Yeah, I can try just leaving the 'No more quests available' blanc and add custom commands with text to them and that you need a perm you get at the end of the quest to see that message.
