### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by ElementalRealm** [FlyingPikachu/Quests#300]
It's not a real problem it's mor a question.
My server will be almost based on your plugin. Is there a way to have a personal contact of you to personalizate the plugin (not much work) even if for that i need to donate?

Like a discord or skype

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests. Unfortunately, I do not provide personal contact information, largely because I am not willing to take on paid work. Although I appreciate the offer, it would be best to simply open an issue here whenever you'd like something fixed/added, and hopefully I'll get to it sooner than later.

**Comment by ElementalRealm** [comment]
Thanks for the reply. Once i get all the NPC's placed and start working on Quests ill talk with you.
