### ISSUE TITLE
Does not complete 

### ISSUE THREAD

**Issue by QueenKisaki** [FlyingPikachu/Quests#31]
Spigot 1.11.2 and Quests 2.8.7
No errors in console.
Quest with issue https://pastebin.com/jSjRpwxF that you tried to duplicate and had no issue, but doesn't mean other people are not having.
And a 46 second video link to show you the issue at play (if it helps) https://youtu.be/xkbj3eHqBZE

The other one you replicated with the fairies is the same issue. turning in a completed quest but its not registering as complete. Nothing to do with mythicmobs or even the items being turned in. 
(I love the quests plugin, I'm not trying to sound upset or anything, just trying to help fix a big problem. And I have plenty of time to test all this out before opening.)

**Comment by FlyingPikachu** [comment]
Although others may be having the issue, know that there's little I can do until there's a _related_ error or a way to replicate it. The video doesn't provide much insight other than that you didn't get a reward after the quest _appears_ completed, but thank you nonetheless!

Proof I successfully completed the quest - http://imgur.com/a/DX5FP

If you would, go your `/Quests/data/yourUUID.yml` and post its contents (I'd like to see whether the plugin considers your quest to be done internally or not). For example, [mine looks like this](https://pastebin.com/GNZSFLnH). You can find your UUID by [typing your MC name here.](https://mcuuid.net/)

**Comment by QueenKisaki** [comment]
https://pastebin.com/BRNiEHNH my data file. I have redone this quest over and over and it only will complete when forcing it.

**Comment by FlyingPikachu** [comment]
I see the plugin considers the quest done for me, but not for you. We're running the same Spigot and plugin versions, so it puzzles me what could be different between our environments. Rather than wonder, please give this version of the plugin a try:

https://www.dropbox.com/s/z71rvsyn6dffao6/Quests-2.8.8-test.jar?dl=0

As soon as you talk to the NPC, your player should receive a few debug messages in chat. Please take a screenshot of those messages and post them back here :)

**Comment by QueenKisaki** [comment]
![2017-07-08_10 11 31](https://user-images.githubusercontent.com/22261674/27986555-f3726e96-63c5-11e7-916b-fd012e854bf6.png)

**Comment by QueenKisaki** [comment]
I went ahead and tested it again on the Fruit quest: 
![2017-07-08_10 15 19](https://user-images.githubusercontent.com/22261674/27986581-749ffa9c-63c6-11e7-9c0c-7ea6ddf0c83d.png)

**Comment by FlyingPikachu** [comment]
Aha! This is related to https://github.com/Blackvein/Quests/issues/297 whereas, in your case, the NPC name and Natural Fruit name `contains` the color green. Quests uses that color internally to determine whether a quest is finished, since all (Complete) messages are green. An oversight on Blackvein's part.

Here's a build which checks if the message `startsWith` green instead (and a few more debug messages in case I'm wrong). If it works, let us know! If not, please post the new messages.

https://www.dropbox.com/s/1zs910j3jws7nda/Quests-2.8.8-test2.jar?dl=0
**Make sure to delete the previous test jar ;)

**Comment by QueenKisaki** [comment]
Oh my goodness it worked :D 
![2017-07-08_14 28 20](https://user-images.githubusercontent.com/22261674/27988557-c5ddd2f8-63e9-11e7-85a2-8acbf21f089d.png)
![2017-07-08_14 30 54](https://user-images.githubusercontent.com/22261674/27988566-1562615e-63ea-11e7-915d-4581ee9c0857.png)

**Comment by FlyingPikachu** [comment]
Great! The latest dev build will contain this fix without the debug messages. Thanks!

http://ci.ac3-servers.eu/job/Quests/140/
