### ISSUE TITLE
Questadmin reload generates internal error

### ISSUE THREAD

**Issue by james8470** [FlyingPikachu/Quests#311]
Quests: 2.60 (latest for 1.9, right?)

Consol screenshot: (this is all it _ever_ spits out all the time) https://gyazo.com/e26ec4d355d50faadf68fa361779d3df

How it happened: Was working earlier today, then I tried to make a quest with an item reward, the fist option was "(&7) - null", ignoring this I made the quest and did /questadmin reload, then the internal error pops up. Reloaded server, quest was deleted. Now, any attempts at /questadmin reload fails, and also making new quests outright fails as well

Please help!
-James

**Comment by meegamax** [comment]
I'm having a similar issue is this normal????


![2016-04-21_20 26 19](https://cloud.githubusercontent.com/assets/18221830/14728997/60cb434c-07ff-11e6-80fc-966331d8425f.png)

**Comment by james8470** [comment]
Well, that actually looks like something is wrong with your config, you might have to delete it and let it reload if you can't find the error, this means losing your quests/events. 

OR it might be that you have the wrong version. If your playing 1.9 for example, 2.60 is the version compatible. You can look back on the quests bukkit page for earlier versions on the left tab.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Still need help with my problem please! It's a big issue for my server!

**Comment by FlyingPikachu** [comment]
Unfortunately if that's all it spits out then that error isn't very helpful for narrowing down the issue. Are you sure there isn't more to it?

**Comment by james8470** [comment]
@FlyingPikachu Thank you for the reply!
I am serious, that is all it ever spits out except when it starts up, I will get a screenshot of startup this afternoon.

-James

**Comment by james8470** [comment]
@FlyingPikachu 
This is the only quest info it displays:
https://gyazo.com/947455debb41d0c152f13f0e95f7f799
However, theirs also an extension plugin to quests which fails to load:
https://gyazo.com/c224a54d160955959d0b04bbec5f2708

Will try running without that other plugin
Thanks, James

**Comment by FlyingPikachu** [comment]
Also try fixing that NPC id error. The Citizens NPC id number for the "testing" quest in your config is invalid.

**Comment by lscapa** [comment]
I've got a very similar issue as well. (Quests 2.6.0 - Citizens 2.0.17-SNAPSHOT)
Updated the default Catch Fish quest to start at NPC #8 Merchant.
Error on reload, and quest is now not available.
Here's the error log that is recorded.

01.05 18:51:35 [Server] INFO ... 15 more
01.05 18:51:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:788) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:807) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.adminReload(Quests.java:884) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.reloadQuests(Quests.java:2661) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:2901) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.loadRewards(Quests.java:2935) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.checkList(Quests.java:4992) ~[?:?]
01.05 18:51:35 [Server] INFO Caused by: java.lang.NullPointerException
01.05 18:51:35 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
01.05 18:51:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v2.6.0-b99
01.05 18:51:35 [Server] ERROR null

And then the logs continues to error with:
01.05 18:51:35 [Server] INFO ... 15 more
01.05 18:51:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.onCommand(Quests.java:788) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:807) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.adminReload(Quests.java:884) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.reloadQuests(Quests.java:2661) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:2901) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.loadRewards(Quests.java:2935) ~[?:?]
01.05 18:51:35 [Server] INFO at me.blackvein.quests.Quests.checkList(Quests.java:4992) ~[?:?]
01.05 18:51:35 [Server] INFO Caused by: java.lang.NullPointerException
01.05 18:51:35 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
01.05 18:51:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:51:35 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v2.6.0-b99
01.05 18:51:35 [Server] ERROR null
01.05 18:49:52 [Multicraft] lscapa ran command Message of the Day
01.05 18:49:52 [Connect] User lscapa, IP 108.230.232.98
01.05 18:49:52 [Server] INFO UUID of player lscapa is 91b8a5a7-fa59-4963-b277-f8f249f890b2
01.05 18:48:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
01.05 18:48:40 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:48:40 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:48:40 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:48:40 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:48:40 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:48:40 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot192.jar:git-Spigot-e6f93f4-935f18b]
01.05 18:48:40 [Server] INFO at me.blackvein.quests.Quests$1.run(Quests.java:220) ~[?:?]
01.05 18:48:40 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:2901) ~[?:?]
01.05 18:48:40 [Server] INFO at me.blackvein.quests.Quests.loadRewards(Quests.java:2935) ~[?:?]
01.05 18:48:40 [Server] INFO at me.blackvein.quests.Quests.checkList(Quests.java:4992) ~[?:?]
01.05 18:48:40 [Server] INFO java.lang.NullPointerException
01.05 18:48:40 [Server] WARN Task #15 for Quests v2.6.0-b99 generated an exception

**Comment by james8470** [comment]
@FlyingPikachu 
**I found a fix,** I just when in the config, found the "&7-null" under item rewards, deleted it, reloaded and it fixed.
I also realized the extension plugin needed to be in modules folder, opes! xD
=-=-==-=-=-=-=-=-=
As for the rest of you, good luck. I'll leave this open for you. Again, it looks like a config error and the only fix I know of it to delete your config, thus losing all of your quests/events. BUT, @lscapa maybe just try deleting "Catch Fish" in the config? Make a backup first!

- Thanks anyways FlyingPikachu,
**Big fan of you plugin! ^_^**
James
