### ISSUE TITLE
[REQUEST] Disable YES\NO chat confirmation

### ISSUE THREAD

**Issue by DarwinTrue** [FlyingPikachu/Quests#325]
Please add an option to disable confirmation when taking quest.

**Comment by FlyingPikachu** [comment]
Kindly provide a scenario in which this would be useful.

**Comment by Volkenstein666** [comment]
Quest acceptance via typing in the chat field when using npc's should just be eliminated. My experience is most of the player base is extremely confused due to either young age or something and anything that isnt done via the gui throws them for a loop. Im not kidding- theyre really too dumb to type 1, 2, yes, or no in the chat field. I use chat field acceptance when priming signs for quests but thats it.

**Comment by FlyingPikachu** [comment]
@Volkenstein666 Thanks for your input. As you've noted along with your comment in #351, the show-GUI option is a good workaround for those that do not wish to use chat confirmation. However, there must be _some_ way for players to accept Quests if Citizens is not installed.

Closing due to lack of response from OP.
