### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by TheOtakuJames** [FlyingPikachu/Quests#330]
Hi there,

I am using the most recent Dev build of Quests, and I am constantly being spammed in Console with the following:
http://pastebin.com/cyaN4k0j

I have tried removing the things from console, along with changing them and reloading the plugin multiple times...
How can this be fixed?

**Comment by Zalakoth** [comment]
From what it looks like, you tried to blacklist certain players from doing a specific quest by typing in their username under "Quester-Blacklist"

The issue here is saying that you typed their Usernames, when the document requires their UUID. (Which is a long string of code that is unique to each player.) My best bet would be to remove the usernames from the quester-blacklist, run the server, and then blacklist them in-game from doing quests by using /questadmin commands. If that is not possible, find a way to get there UUIDs, and then copy paste those into the document. If neither of these work, post back under this thread. (Again I am not an admin, I just try to help.)

**Comment by FlyingPikachu** [comment]
@TheOtakuJames Zalakoth's answer is likely the proper fix.

**Comment by nottobyxxx** [comment]
i have the same problem and it did not work.

**Comment by nottobyxxx** [comment]
It worked for me

**Comment by FlyingPikachu** [comment]
Please create a new, updated ticket if this is still an issue. Thanks!
