### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by InfroDaz** [FlyingPikachu/Quests#333]
I don't think that this is new, but the plugin really misses dialog system.

**Comment by FlyingPikachu** [comment]
Dialog system? Please elaborate.

**Comment by InfroDaz** [comment]
Well, I mean't that before taking a quest an NPC would be asking you several question with different options. And what is more necessary the Talk to NPC objective which is not giving a possibility to add different options to talk about.

**Comment by FlyingPikachu** [comment]
The key words in your reply are "before taking a quest". The only options for conversing with an NPC _during_ a quest are Events and Custom Objectives. Anything that happens _before_ taking a quest (besides the obligatory ask-message) really isn't of concern to this plugin. In other words, dialog trees should be managed by a module, Denizen script, or external plugin per your needs

If you find a plugin that's particularly good at setting up NPC dialog prior to Quests, I'd consider hooking into it for a dependancy, but otherwise it's not Quests' job to manage that.
