### ISSUE TITLE
Execute Death events after respawn 

### ISSUE THREAD

**Issue by ScuroK** [FlyingPikachu/Quests#338]
Death events should be executed after the player respawned.
Right now Events like "teleport to quest start" will not work because the plugin tries to execute the teleport/teleport command while the player is death.

**Comment by FlyingPikachu** [comment]
Assuming you're now on dev version 3.2.8

Please provide an example quest from quests.yml to test with (upload or use Pastebin.com; do _not_ copy/paste).

**Comment by ScuroK** [comment]
Nah i downgradet again because the redo-delay option is a must have for me.
I deleted the quest where i wanted to use the death-events. but essentially i just want to teleport the player somewhere (for exampl where the quest starts) after he died.

**Comment by FlyingPikachu** [comment]
Since you no longer have a way to replicate the issue, I'm closing this ticket. Feel free to request it be re-opened once you have an example quest.

**Comment by ScuroK** [comment]
@FlyingPikachu 

Here is an example called TEST:

https://pastebin.com/tLXp5zdb
https://pastebin.com/gQs4iNuj

the teleport event (TEST) will not execute because the player is in death screen.

**Comment by FlyingPikachu** [comment]
I was able to replicate the issue. A solution for this is a bit complicated. Most of the time waiting for the player to respawn to teleport would work, but there's problems like 1) what if the player quits the game while dead, 2) what if the server restarts while the player is dead, and 3) what happens to a player's items that dropped before death?

To avoid all those conditions would require keeping track of whether a player is dead or alive at all times, which isn't a good use of resources. Alternatively, issues 1 and 2 could be fixed by first forcing the player to respawn with `Player.spigot().respawn()` but the keyword in that code is "spigot". Currently Quests is still supporting Bukkit 1.7.9, so calling Spigot code would break the plugin for those few Bukkit-only servers.

As far as I can tell, there isn't really a good way to fix this. Unless someone can think of a way or Quests drops 1.7.9 support (unlikely), I'm afraid your best bet is to use items or another plugin to ensure the player doesn't die right before the event fires.

**Comment by ScuroK** [comment]
There are minigame plugins which are compatible with both and they will „respawn“ you without a death screen i think. But im not sure.
