### ISSUE TITLE
item durability example:373:3

### ISSUE THREAD

**Issue by shootcraft** [FlyingPikachu/Quests#361]
Hello , quests plugin, stage of block placing seem cant receive item id but have to type the item name instead, some items like head have it durability such as 373:3, and I cant insert the item in. it will be error

**Comment by FlyingPikachu** [comment]
https://github.com/FlyingPikachu/Quests/wiki/Item-Formatting

Read the last paragraph.

**Comment by shootcraft** [comment]
but is not working out
          place-block-names:
          - 'name-COAL:data-1'
          - '109'
          - '44'
          - '139'

**Comment by FlyingPikachu** [comment]
@shootcraft Where is your "amount-1" tag? Also item numbers (109/44/139) are NOT accepted.

Please delete and recreate your quest using the in-game menus. If that still doesn't work, create a new issue and include your quests.yml

**Comment by shootcraft** [comment]
it is not working, If I create the quest stage ingame, it tells to enter block name and so it only accepted block name and some block name I cant even find it such as chiseled smooth brick on the link. That why I am trying items id with durability but is not working

**Comment by FlyingPikachu** [comment]
It is not working because item IDs are not accepted. So stop trying that.

Chiseled Stone brick would have the name of SMOOTH_BRICK and a data of 3.

Block data source - [http://minecraft.gamepedia.com/Stone_Bricks#Data_values](url)

If you are still having trouble, ask for help on the Spigot forum. Thanks!

**Comment by shootcraft** [comment]
amount and data is not supported for placing block stage it only support items name
https://cloud.githubusercontent.com/assets/20242540/16576007/eceb5e4e-42be-11e6-8d83-00290b8f7c88.png

**Comment by FlyingPikachu** [comment]
@shootcraft That is not what it's telling you. It is saying the item _name_ is invalid. So it might not be SMOOTH_BRICK. Try using the "add item from hand" option in-game to get the proper name.

**Comment by shootcraft** [comment]
okay, how can i add chiseled stone brick since Id and name-SMOOTH_BRICK:amount-1:data-3 were not accepted
https://cloud.githubusercontent.com/assets/20242540/16591074/e6420414-430c-11e6-9e9c-34f68f51dca3.png    please dont reply me as fast as possible I am about to sleep I will wait

**Comment by FlyingPikachu** [comment]
@shootcraft I don't know what you've done... even the error it gives you should not appear like that.

Turns out SMOOTH_BRICK is correct, so your quests.yml config must be wrong. Here is an example of the formatting, which I have tested and works - http://pastebin.com/3npyG583

I am not your parent, thus am not responsible for your sleep schedule. If you don't want to stay up past your bedtime, don't read/reply to this comment.

If you still need help, post your quests.yml file (upload it to a file-sharing site, do not copy and paste). Otherwise I will close and mark this invalid under the assumption of user error. Thanks!

**Comment by shootcraft** [comment]
It will work on item delivery stage but block placement stage won't work

**Comment by shootcraft** [comment]
In my opinion, the error is name-SMOOTH_BRICK:amount-1:data-3 was not supported for place block stage, could you add id support ?

**Comment by FlyingPikachu** [comment]
Closing due to lack of quests.yml as requested. ID support will not be added as item IDs are deprecated.

http://www.javaminecraft.com/bukkitapi/org/bukkit/inventory/ItemStack.html#getTypeId()

**Comment by shootcraft** [comment]
So how can I add chiseled stone brick for my  quest ?

**Comment by shootcraft** [comment]
Here the yaml file http://pastebin.com/XRv1u1Gd

**Comment by shootcraft** [comment]
Please at least tell me a temporary solution, I have already setup all my quests and awaiting this bug to be fix, If is not fix I cant further my server update

**Comment by shootcraft** [comment]
Hello, I am sorry for disturbing could you  reply me with an answer ?

**Comment by shootcraft** [comment]
I am serious about this bug, Please kindly take some action thank you

**Comment by shootcraft** [comment]
Um Could you please be reply, I have awaiting your message everyday

**Comment by FlyingPikachu** [comment]
This issue has been closed. Please create a new issue with your yaml file. Make sure to point out which quest(s) have the problem.
