### ISSUE TITLE
Magic no kill journal score

### ISSUE THREAD

**Issue by McJoker123** [FlyingPikachu/Quests#404]
Your plugin does not consider journal murder as magic!

Is it clear now?

**Comment by FlyingPikachu** [comment]
If I understand correctly, you are requesting that kills made using the Magic module show Magic as the source in the Quests Journal. However, this is something that the module would need to implement rather than Quests itself. Please seek help from the author of Magic - https://github.com/elBukkit/MagicPlugin/issues
