### ISSUE TITLE
Multipe GUI Display item usage

### ISSUE THREAD

**Issue by GSerum** [FlyingPikachu/Quests#430]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Not really a problem, i think it might be intentional, but i am running out of items to use for the GUI Display, is there a way to allow the use of items multiple times? I don't see the problem with htis.

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
no

**Comment by FlyingPikachu** [comment]
You must have an impressive GUI! Unfortunately, this isn't possible because Quests doesn't store any extra information along with the item - it just associates Dirt with one particular quest, Stone for another, and so on.

That said, it's totally possible to attach some extra info to allow using multiples of the same block/item. However, with 1.13 here and so much to do, this is really low priority. I'll leave this open for a while in case someone wants to submit a PR for this, but I can't give any estimate as to if/when I can get to adding this myself.

**Comment by FlyingPikachu** [comment]
I've looked into this recently and, while it is certainly possible, I've decided not to proceed as there are some undesirable effects of including this enhancement:

1. Users may be confused seeing multiples of the same item, especially if a server owner were to make a GUI entirely of Dirt, and...
2. ...although I can't imagine anyone actually doing that, MC 1.13 has introduced a plethora of new items which should make it incredibly difficult to run out of items.
3. If it gets to the point where someone has exhausted all 967 items in a single GUI, it probably goes without saying that such a ginormous GUI should not exist in the first place, however...
4. ...having that many quests each with a different item across multiple GUIs is understandable. Still, it seems unlikely that any server to date would have that many quests available.
