### ISSUE TITLE
currentStage was null for ecf3cb28-4bac-321d-8d8b-3669239cc9f8 on command

### ISSUE THREAD

**Issue by smartmadio** [FlyingPikachu/Quests#432]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.3.4

(__Required__) Please describe the problem and how to replicate it. Any console errors?
`[07:34:37] [Server thread/ERROR]: [Quests] currentStage was null for ecf3cb28-4bac-321d-8d8b-3669239cc9f8 on command`

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
https://pastebin.com/v9h74UuV

**Comment by FlyingPikachu** [comment]
Are you sure this is the correct quest for that error? This error happens when a player types a command in chat, whereas that command reward in your quest is dispatched from the console.

Next time you see this error, take a look at the player's data in Quests/data/ecf3cb28-4bac-321d-8d8b-3669239cc9f8.yml (or whichever player uuid is given in the error) and upload the quests listed there.
