### ISSUE TITLE
Add possibility

### ISSUE THREAD

**Issue by FyFou57** [FlyingPikachu/Quests#446]
Hello,

I would like your plugin to add new possibilities (stage)

//Craft a number of item
(In this exampl, craft 5 diamond_sword)

craft-item : DIAMOND_SWORD 
- 5

//Your plugin contains location options, reach coordinates for example, but reach a place, and browse a number of block is totally different
(In this exampl, brows 5000 blocs in the nether)

location-parcour : 5000 
world: nether

//Possibility of recovering the crafts
(in this exampl, eat 5 pomme cheat

eat-item  :  GOLDEN_APPLE:1
- 5

Your plugin has serious problem to define items, many object can not be defined, for example, "placing ENDER_CHEST" is not possible, the plugin does not recognize ENDER_CHEST. Use creeper eggs is not possible, destroy X number of wheat, destroy X number of pumpkin, is not possible

A lot of little negative point that poisons the plugin

**Comment by FlyingPikachu** [comment]
Thanks for using Quests!

Craft objective has been suggested before, see #14. To quote the ticket linked there (which also applies to eating and other item-related tasks):

> I began work on this but have decided not to proceed. I thought about everything one could do to an item - craft it, smelt it, brew it, rename it, use it, toss it, break it, repair it, destroy it, et al. It would be great to cover each of those individually, but I feel as though delivering an item covers most, if not all of these, so long as the player's environment is controlled (including enchanting?). And considering how crowded the Stage editor is already, this just doesn't seem feasible.

Walking objectives could be a nice addition, but can be costly in terms of resources (see https://github.com/FlyingPikachu/Quests/commit/87edb98c3e815a7e8b23446d217477dfff7c8c64 for a recent example of what I mean). Certainly possible, but I also have yet to see any major demand for a walk objective. Will leave this open for further discussion on it.

The material enum was reworked, so it's entirely possible that ENDER_CHEST doesn't work (see if LEGACY_ENDER_CHEST works?). Make sure to use CROPS or LEGACY_CROPS rather than "wheat" ("wheat refers to the item, no the block).  Here's the full list you can peruse:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

Creeper eggs are a known issue, see #107

**Comment by FyFou57** [comment]
LEGACY_ENDER_CHEST don't work, i suppose LEGACY_CROPS don't work too.

I understand that you can not add some things that are too laggy for the moment. 
i hope one day you can add it without lag, it will change everything

**Comment by Ryan56k** [comment]
When can we expect to see potions work with the quests? Seriously love the versatility of this plugin and that would aid to enhance it.

Thank you!

**Comment by FlyingPikachu** [comment]
Would like to note that potions should be working with the latest commit. Leaving this open until the Ender Chest issue can be addressed.

**Comment by FlyingPikachu** [comment]
Closing as, with recent changes to how item names are addressed, it would be best to handle this in a ticket using a more recent version of Quests. Please direct all ENDER_CHEST issue comments to #507
