### ISSUE TITLE
1.13 Bugs

### ISSUE THREAD

**Issue by AsperionMC** [FlyingPikachu/Quests#448]
**What is your Quests version / build number (do _not_ say "latest")?**
(QUESTS-3.3.6 [Jenkins: #480)]
If it helps,
Spigot: Spigot-69774b3-8e87d03 (MC: 1.13 R0.1)
Citizens: Citizens v2.023-SNAPSHOT (build 1562)

**Please describe the problem and how to replicate it. Any console errors?**

(PlayerDeath): https://hastebin.com/amuhejaziw.cs
(NPCRightClick): https://hastebin.com/iyilukinil.cs

1) For PlayerDeath, it happens randomly on death. There is no specific cause of this from what I can tell it just throws out an error.

2) For NPCRightClick, from what I have noticed is that it will not take the players item and shoot out an error. Works fine in the start but eventually will start to bug out. This also causes significant lag on my server. Removing the plugin promptly discontinues the lag issue.

I understand I am using a Dev Build and errors are expected, but I have decided to let you know of this error.

**Can you provide an example quest from quests.yml _using Pastebin.com_?**

From what I can tell it's when players are delivering an item to an NPC, so here's that quest:
- https://pastebin.com/0NAw2tjD

(while on this topic, is there way to have players deliver more than 64x items at once than the monstrosity I have setup?)

**Comment by FlyingPikachu** [comment]
Unfortunately. your first error (PlayerDeath) just indicates that the server experienced a problem with a Skeleton entity. Unless there is more to the error after that last line, there's no way for me to help diagnose this for a workaround.

![quest_done](https://user-images.githubusercontent.com/2267126/43681909-2174a51c-9830-11e8-8a9b-2db3dc0f0af1.png)

Your second error is definitely a problem with Quests, but as you can see, I wasn't able to replicate it on a 1.12.2 server. Since I don't have a 1.13 set up, the next available dev build will place additional info in the console next time the error happens (as well as notify the player). Once you install that build, please post back here with the console information if it happens again!

**Comment by AsperionMC** [comment]
Thank you for the response, I will update to the latest dev build and inform you of errors which come from it.

**Comment by Sprungente** [comment]
I found another issue with 1.13.1 but i don't know what the reason is. 

https://pastebin.com/rQG2dY5N

maybe you have an idea
