### ISSUE TITLE
Quests no longer activate, cannot set any locations (No right clicking and no more effects above NPC heads(

### ISSUE THREAD

**Issue by Redzilla22** [FlyingPikachu/Quests#451]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
3.3.4-b316

(__Required__) Please describe the problem and how to replicate it. Any console errors?
I do not have access to the console, but I was discussing with our developers what might be the problem, at the same time this started happening our NPCs that were sitting all created armorstands and a mass of npcs were made, I don't actually know the problem other than the developers said there was an error for "blackveil" and something about an effect.

**But overall the problem seems to be anything that requires right clicking with quests.**

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
I do not have access, but is there anyway you can tell us what might've happened.

**Comment by FlyingPikachu** [comment]
Probably "Blackvein", which was the previous developer of this plugin. Chances are your developers are using an old Bukkit build on accident. Current builds of Quests are hosted exclusively on Spigot.

https://www.spigotmc.org/resources/quests.3711/

Because you do not have access to the actual error, I'm afraid there's nothing else I can do. Once your developers install a recent build from Spigot, have them post a new Github issue with any questions. Thanks!
