### ISSUE TITLE
EffectLib Support 

### ISSUE THREAD

**Issue by Worlfy** [FlyingPikachu/Quests#455]
Hi hi,

I hope I'm doing this right:
I was wondering if we could get EffectLib support, especially in the 2 config.yml settings

`npc-effects:
  enabled: true
  new-quest: spell
  redo-quest: angry_villager`

Something like that could eventually become:

`npc-effects:
enabled: true
new-quest: effectlib:helixeffect,radius=10,particles=20,strands=5,particle=FLAME,curve=3
redo-quest: effectlib:warpeffect,radius=2,particles=10,particle=FIREWORKS_SPARK,grow=0.1,rings=10`

These are the "reasonable" variables we should be able to change within the effect.
This would allow us to make great things such as: 
![image](https://user-images.githubusercontent.com/8803519/43993456-fea0fadc-9d8d-11e8-9272-ef0709bb77db.png)
![image](https://user-images.githubusercontent.com/8803519/43993663-72d2da1c-9d91-11e8-8ca6-7379ba366d46.png)
_Honestly, AnimatedBall is most likely the best one 🥇_ 

Thanks for hearing me out,
zThana

**Comment by FlyingPikachu** [comment]
This sounds great, but I'm afraid I have bigger things on my plate at the moment. If anyone would like to submit a pull request, I'm all ears.

**Comment by FlyingPikachu** [comment]
So I've looked at this some more and, although this would be pretty easy to add, the EffectLib project does not currently have a presence on Spigot. Quests only links with plugins advertised on spigotmc.org as a courtesy to operators, both for security and longevity, as the future of BukkitDev as a whole is... unreliable.

If the original author @Slikey or an active maintainer like @NathanWolf would like to publish EffectLib on Spigot, I'd be happy to integrate the library in a similar fashion as [Magic](https://github.com/elBukkit/MagicPlugin) has.

**Comment by NathanWolf** [comment]
Magic actually shades EffectLIb in, and that's kind of how I'd recommend using it (personally).

I will say it won't be super easy to convert the format suggested above to what EffectLib wants, though- I mean ideally you'd be able to configure effects with a Yaml block, so you don't have to do the work of converting the config to the internal effect representation.

Anyway, if shading is not acceptable then I can add a SpigotMC page for EffectLib (er.. I think, given that it's not technically mine but I think it's ok...?) but I honestly probably wouldn't have a lot of mental capacity to support it, I'm barely able to keep up with supporting Magic these days.

**Comment by FlyingPikachu** [comment]
Think I'd prefer not to shade simply because of the extra work and file size that requires, but it's not off the table. Doubt the format OP suggested will be used verbatim, but I did see on the BukkitDev page that EffectLib has "Configuration-Driven Effects" which I might take advantage of.

The [MIT License](https://tldrlegal.com/license/mit-license) allows distribution as long as the license and any copyrights are included, the latter of which I assume is irrelevant (and also assuming it is still under MIT as the BukkitDev page lists it as). The real roadblock is the [Spigot resource guidelines](https://www.spigotmc.org/threads/premium-resource-guidelines.31667/), which state the following:

> You must be the original author and copyright holder of the work which you are submitting.

If you were to fork Slikey's repository into your own and tweak it, it's my understanding that would effectively make you the "original author" (of that fork). That's exactly what I did for Quests, albeit with Blackvein's blessing, so it couldn't hurt to ask Slikey first _if_ he/she is reachable. No support expected :)

**Comment by NathanWolf** [comment]
Ah yeah it's the Spigot guidelines I'm a bit worried about. I definitely have Slikey's permission to fork, but I don't really want to do that since I a lot of people know the repo and rely on it.

I also don't necessarily want to start a spigotmc page I'm not going to be able to maintain or support myself.

Hmmm. Well I'll give it some thought. Maybe there would be some way to hook the two together via a separate plugin that hooks into the Quests API somehow?

**Comment by FlyingPikachu** [comment]
That's perfectly understandable. Maybe one day the project will find its way toward Spigot. Either way, I appreciate the input.

A gateway plugin is certainly possible, but that still relies on EffectLib's host not expiring. Forgive me for my distrust of BukkitDev, but I feel it has seen better days.

**Comment by NathanWolf** [comment]
I 100% agree re: bukkitdev. It still completely baffles me how many people get my plugin from there. I rarely update, and provide little to no support there.

I'll maybe see about adding a spigotmc page. I am a contributor on the github repo, maybe that's good enough?

**Comment by FlyingPikachu** [comment]
Closing as there is no indication EffectLib will be released on Spigot anytime soon. Feel free to request re-open should that change in the future.
