### ISSUE TITLE
I can't translate to my language !!

### ISSUE THREAD

**Issue by attackgamingvn** [FlyingPikachu/Quests#481]
Hello author
I'm using your plugin
But I do not know how to convert to my language
I downloaded the string.yml file
But I do not know where to put it
please help me !

**Comment by attackgamingvn** [comment]
i'm using 3.3.4
When i load this plugin
i can't see folder "lang"
so i can't stranslate to my language
Please fix this bug,my server need QUESTS

Vào Th 2, 24 thg 9, 2018 vào lúc 10:50 FlyingPikachu <
notifications@github.com> đã viết:

**Comment by attackgamingvn** [comment]
https://pastebin.com/7vcBcsyU
too much bug
i can't set delivery items

Vào Th 2, 1 thg 10, 2018 vào lúc 09:56 Nhật Nam Ngô Trần <
ntn26gaming@gmail.com> đã viết:

**Comment by attackgamingvn** [comment]
I'm using Windows 10,My quests version is 3.4.3
This is problem when i use the command /questsadmin reload
https://imgur.com/a/asdwiyk
And this is folder quests when i just run it,i don't see any "lang" folder:
https://imgur.com/WscnT3B

**Comment by FlyingPikachu** [comment]
@attackgamingvn Please give the following dev build a try once available, then post the resulting your startup log:

http://ci.ac3-servers.eu/job/Quests/509/

**Comment by attackgamingvn** [comment]
This is log:
https://pastebin.com/Eg2z76Eq

**Comment by FlyingPikachu** [comment]
@attackgamingvn I see you also have Essentials installed. According to these lines, Essentials isn't able to set up most of its configuration files either (unless this is the first time running it):

>[17:39:14] [Server thread/INFO]: [Essentials] Enabling Essentials v2.15.0.1
[17:39:14] [Server thread/INFO]: Creating config from template: C:\Users\MyPC\Desktop\Minecraft Sytems\Project\thunghiem\plugins\Essentials\config.yml
[17:39:15] [Server thread/INFO]: Creating config from template: C:\Users\MyPC\Desktop\Minecraft Sytems\Project\thunghiem\plugins\Essentials\kits.yml
[17:39:15] [Server thread/INFO]: Attempting to convert old kits in config.yml to new kits.yml
[17:39:15] [Server thread/INFO]: No kits found to migrate.
[17:39:15] [Server thread/INFO]: [Essentials] Starting Essentials ban format conversion
[17:39:15] [Server thread/INFO]: [Essentials] Starting usermap repair
[17:39:15] [pool-5-thread-1/INFO]: Creating empty config: C:\Users\MyPC\Desktop\Minecraft Sytems\Project\thunghiem\plugins\Essentials\upgrades-done.yml
[17:39:15] [Server thread/WARN]: [Essentials] Missing userdata folder, aborting
[17:39:15] [Server thread/INFO]: Creating config from template: C:\Users\MyPC\Desktop\Minecraft Sytems\Project\thunghiem\plugins\Essentials\worth.yml

Its pretty unlikely both Quests and Essentials have the same bug, so this is likely an issue with your folder permissions.

Since you're on Windows 10, right-click on your /plugins folder, select Properties, and go to the Security tab. Click "Advanced" and then, in the Permissions tab, select "Change Permissions". Choose "Add" and in the Select User or Group window, type "everyone" in the text box. Click "Check Names" and then choose "OK". Continue clicking "OK" until all windows are closed.

Now, try running the server and see if the issue is resolved.

**Comment by FlyingPikachu** [comment]
If that doesn't fix the problem, you could also try running your server as an Administrator. Right-click whatever file/method you use to start your server, and select "Run as Administrator".

**Comment by FlyingPikachu** [comment]
As mentioned in #538 another cause might be your folder permissions. Please feel free to request this issue be re-opened if none of the fixes work for you.

> If you're on Windows, right-click on your /plugins folder, select Properties, and go to the Security tab. Click "Advanced" and then, in the Permissions tab, select "Change Permissions". Choose "Add" and in the Select User or Group window, type "everyone" in the text box. Click "Check Names" and then choose "OK". Continue clicking "OK" until all windows are closed.

Now, backup your Quests folder and delete the original (you can copy over your data from the backup later). Try running the server, allowing Quests to generate new files, and see if the issue is resolved.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by attackgamingvn** [comment]
Hello FlyingPikachu
I tried the options you mentioned above but not successful
Last night,i'm tried to run Quests-3.0.0-Naomi and this version have folder "lang" 
And this is my latest log:
https://pastebin.com/rBQKC5p0
Thanks u so much
