### ISSUE TITLE
Add Translationfile

### ISSUE THREAD

**Issue by Sprungente** [FlyingPikachu/Quests#5]
Hey Pikachu

I know everybody can change messages, but it isn't easier when language-files are in the pluginfile like de Fr and i don't know how many language exist on our world. 

When a translation missing, than he shouls automatically take in english. 
So the full translation is in en.yml and some translated strings are in a language file. I have seen something like that somewhere else.

Who is updating the translationfile? I think you have many many people there use this. anyone will do this i'm sure.

**Comment by FlyingPikachu** [comment]
@Sprungente In `Quests/config.yml`, the default 'language: en' setting can be changed to anything. For example, we change it to 'language: popcorn'. On server startup, Quests will look at `Quests/lang/popcorn.yml` and use that for language (if there is an error loading, it will default back to English).

If you would like a certain translation, you'll want to hunt down someone else's file or make your own. I feel I should not officially add more language files like French or Deutsch because I have no way to check them for errors. Perhaps if anyone posts their files here or on Spigot, I could make a Wiki page dedicated to everyone's translations.

The English file is typically updated by myself.
