### ISSUE TITLE
Worldguard blocks Citizens or Quests idk.

### ISSUE THREAD

**Issue by TheBosslandGMBH** [FlyingPikachu/Quests#52]
I have a problem with the plugin quests.
after i protect a region with Flag Build deny, the citizens plugin wont work so players cannot accept the quests.
here is a screenshot from the error message
http://prntscr.com/6fwpvz

is ther eany way to fix it

**Comment by FlyingPikachu** [comment]
That's a) an issue with Citizens, and b) probably intentional. Either report the issue to the authors of Citizens or work around the build flag.

**Comment by Formula350** [comment]
@TheBosslandGMBH Just in case you haven't gotten this sorted out, try setting the region flags USE to Allow, and/or INTERACT to Allow for that region.
/rg flag <region name> use allow
/rg flag <region name> interact allow

If either of them by themselves  doesn't solve the issue, set it so both are enabled.
BTW, to delete any flag that is set on a region, use the same command but do not type anything after the flag. Example: to remove the USE flag only type 
/rg flag <region name> use

Oh and another thing, since regions that are //inside// of other regions always obey the "deny" on any flag, make sure that if the region where your NPC is standing is inside another region, to set:
/rg priority <region name> 1
The <region name> in this instance will be the region that the NPC is in, **not** the larger outside region.
