### ISSUE TITLE
Players Can Remove GUI Menu Items

### ISSUE THREAD

**Issue by mercurialmusic** [FlyingPikachu/Quests#530]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests 3.4.2

(__Required__) Please describe the problem and how to replicate it. Any console errors?
Players are able to remove items from the NPC Quests GUI. Looks like it might be related, but I'm also getting [this error](https://pastebin.com/m3Xgjq5F) in console.

**Comment by FlyingPikachu** [comment]
Looks like an issue with a “Talk to the Apothecary” quest. Could you please use Pastebin to post it from your quests.yml file?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mercurialmusic** [comment]
Huh. Yeah. And that's the one people were reporting being able to take, but it made me nervous about the others. For the GUI I just have a generic potion in there, which is probably what's doing it:
`    gui-display: name-POTION:amount-1`

I had edited this from the config rather than in-game, since it's part of a series of quests that I want to keep in order, and in-game quest editing throws everything out of order. And potions are weird so I was fine with it showing up as the generic potion. Guess I'll do it in game.

**Comment by SparkPitti** [comment]
I have the same problem [Error](https://pastebin.com/p4B15SPA) and [my quest](https://pastebin.com/WDWif23n)

**Comment by FlyingPikachu** [comment]
@mercurialmusic As has become evident by SparkPitti's report, your GUI string is not related. It is an issue with the specific quest I mentioned. Since you did not post the information from your quests.yml as requested, there is nothing I can do to assist you further.

@SparkPitti Thank you for including your quest along with the error. I'll be pushing a fix shortly which should resolve both yours and mercurialmusic's issue.

**Comment by FlyingPikachu** [comment]
Use this dev build - http://ci.ac3-servers.eu/job/Quests/506/
