### ISSUE TITLE
Failed loading lang files

### ISSUE THREAD

**Issue by Straiker123** [FlyingPikachu/Quests#538]
3.4.4 buid 511

i tried remove all files .. reload, restart server .. nothing please help

[23:33:52 ERROR]: [Quests] Failed loading lang files for cs-CZ because they were
 not found. Using default en-US

**Comment by FlyingPikachu** [comment]
Duplicate of #481 

Try the latest dev build and check your folder permissions.

http://ci.ac3-servers.eu/job/Quests/510/

> If you're on Windows 10, right-click on your /plugins folder, select Properties, and go to the Security tab. Click "Advanced" and then, in the Permissions tab, select "Change Permissions". Choose "Add" and in the Select User or Group window, type "everyone" in the text box. Click "Check Names" and then choose "OK". Continue clicking "OK" until all windows are closed.

Now, backup your Quests folder and delete the original (you can copy over your data from the backup later). Try running the server, allowing Quests to generate new files, and see if the issue is resolved.

**Comment by Straiker123** [comment]
solved thanks
