### ISSUE TITLE
Request: Objectives

### ISSUE THREAD

**Issue by GuerreroCraft61** [FlyingPikachu/Quests#552]
Is posible add in the objetives, use commands or complete other quest? It you can use it to make initialy missions to guide the player

**Comment by FlyingPikachu** [comment]
To use commands during a quest, make an Event using _/quests events_
To use commands upon completion of a quest, add a command reward through /quests editor
To require a different quest already be completed, add a quest requirement through /quests editor

**Comment by GuerreroCraft61** [comment]
The command, I mean player use the command to complete the quest, no server use command when complete the quest

**Comment by FlyingPikachu** [comment]
To my knowledge, there is no way to advance a quest when a player runs a command.

**Comment by FlyingPikachu** [comment]
So you want quest A to be completed in order to take quest B?

That's called a quest requirement.  You can add one when creating/editing a quest:

![add](https://user-images.githubusercontent.com/2267126/49749223-b605b280-fc75-11e8-9da5-8d4b897a0bc0.png)

You may benefit from joining the official Discord, where you'll get a faster response to these sorts of questions - https://discordapp.com/invite/d56CQ6e

**Comment by FlyingPikachu** [comment]
...that's still a quest requirement, just in reverse. If the player had already completed quest B, you'll have to make sure it can be taken repeatedly. This is under Editar Planificador -> Set repeat cycle

This ticket is closed. Visit the [Wiki](https://github.com/FlyingPikachu/Quests/wiki) or official Discord for further assistance.
