### ISSUE TITLE
Quests being reset + items with nbt unbreakable error + a lot more bugs

### ISSUE THREAD

**Issue by Borc55** [FlyingPikachu/Quests#591]
Here are a bunch of bugs which are bothering me. Took me a while to write it down.

Using Quests build #573 on 1.13.2 spigot server.

Item delivery quests with NBT tag Unbreakable cause errors after creating & reloading.
Error: https://pastebin.com/fr3272TS
Quest: https://pastebin.com/E3Pdc0KJ
When unbreakable tag is manually removed from quests.yml, reload is successful.
------------------------------------------------------------------------------------------------------------------
After a /quests reload command, all quests that ONLINE people have active get reset.
------------------------------------------------------------------------------------------------------------------
Get to location quest ignores world.
------------------------------------------------------------------------------------------------------------------
Item delivery quests don't tell you what you are supposed to do after you get the phase, or in /quest. Like for example talking to NPCs does - 'Go talk to XX'.
(maybe caused by lang?)
------------------------------------------------------------------------------------------------------------------
You still can't put more than one type of item in item delivery quest. When you add another item in, it throws a red text at you.
------------------------------------------------------------------------------------------------------------------
And lastly, probably the most importantly, because i've seen similar problems here at issues.
I have no idea what causes it, but I'll tell you the exact steps that I did.
This is the quest I used: https://pastebin.com/yr2vveyG
First I brang all the items in one click until I reached phase 5.
Then I separated stack of those items next to each other in my hotbar to 2x 32s.
Then I clicked the second 32 to bring it to the NPC. It took the first 32, nothing out of the ordinary here, because those items were more in front, so quests took those.
Then I restarted the server.
Tried to click the second 32 items to finish the phase. But it said it's not the item, even though it was stacked before I separated it to two 32s before.
I tried doing it two more times with these exact steps. But it didn't happen again.
I have no idea what is causing it, but it does seem kinda random.
The important thing is that the item bug still persists.

I hope it was understandable. English isn't my native language but I'm trying my best.
I don't know why the text got bold, sorry about that, no idea how github works.

**Comment by FlyingPikachu** [comment]
Thanks for the report. In the future, please open separate issues for each problem.

Some NBT tags are not currently supported by Quests. However, I will push a commit shortly that will support the Unbreakable tag.

_/quests reload_ is not a valid command, do you mean _/questadmin reload_ ? If so, the command is working as expected because Quests does not save objective progress to file until it is complete. Thus, when you reload the plugin before an online player has completed their objective, their progress is lost.

The issue with reach-location quests was resolved two weeks ago in 3e5115d64d25345fe03204c7e61f68d813a5f2db. Since you're using build 573, the patch is already present on your server.

The objective prompt for item delivery quests seems to be working just fine, as shown:
![proof](https://user-images.githubusercontent.com/2267126/50467950-847a3000-0973-11e9-8ce4-2242bd2505c6.png)

Also, I was able to add multiple items for delivery just fine:
![proof2](https://user-images.githubusercontent.com/2267126/50468025-cf944300-0973-11e9-93d0-0f3e2e28ee1f.png)

I must request that you open a new issue regarding the 32 item thing, as that looks like it will request extensive testing.

**Comment by FlyingPikachu** [comment]
Use this build for Unbreakable tag support, once available:
http://ci.ac3-servers.eu/job/Quests/575/
