### ISSUE TITLE
Error when someone got killed by a wolf.

### ISSUE THREAD

**Issue by SoraShiunin** [FlyingPikachu/Quests#650]
**What is your Quests version / build number (do _not_ say "latest")?**
3.5.9

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Error when someone was slain by a wolf. Din't happen before or later.
https://pastebin.com/59XdpQJy

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Not related

**Comment by FlyingPikachu** [comment]
Thanks for your report and sorry I hadn't got to this sooner. Because of the recent refactor, I'm unable to access the PlayerListener history for versions of Quests prior to 3.6.0. Please update to at least that version and, if this issue happens again, please open a new ticket with the resulting error.
