### ISSUE TITLE
No delivery Message, completed display name.

### ISSUE THREAD

**Issue by kleinesgumi** [FlyingPikachu/Quests#678]
Quests version 3.6.2-b646

"No delivery Message"
 After a delivery no delivery-messages are shown.

"completed displayname"
In the completed message onlythe Material Name showed up and not the Displayname.
https://abload.de/img/wowylj9y.png

**Comment by FlyingPikachu** [comment]
Thanks for your report. I wasn't able to replicate this, so please provide an example quest from your quests.yml using Pastebin.com

**Comment by FlyingPikachu** [comment]
Now I see what's happening. Delivery messages are only shown when a player delivers _less than_ the required amount of items. For example, if a quest requires 10 ink sacs, but your player delivers 6, a deliver message will be shown.

Since you are only requiring 1 ink sac, it's not possible for the message to be shown. In this case, you can say something to the player using a Complete message (show below):

![complete](https://user-images.githubusercontent.com/2267126/52300941-291a6500-2957-11e9-8b10-8fefd385f483.png)

**Comment by kleinesgumi** [comment]
Quests version 3.6.3-b655

the (Complete Deliver is still MATERIAL Name) not the displayname.
![redrose](https://user-images.githubusercontent.com/3619551/52340785-fd5bb580-2a10-11e9-9d73-9b556ef9cddb.png)

**Comment by kleinesgumi** [comment]
objective-override: 'Deliver a Item to NPC'
not working, the objective-override not working with Delivery they not override.

**Comment by FlyingPikachu** [comment]
The display name issue will be resolved in http://ci.ac3-servers.eu/job/Quests/690/

Note that this build changes the default `translate-items: false` to `translate-names: true`. No action is required on your part unless you wish to disable translation under the new setting name.

**Comment by kleinesgumi** [comment]
objective-override: 
still not working with Devliery in the newest version and the questInvalidDeliveryItem
comes 2 times and rightclick on the NPC.


Displayname now working good :)

**Comment by FlyingPikachu** [comment]
Glad delivery messages and display names are working properly.

Since objective-override was not part of your initial post, please open a new issue.
