### ISSUE TITLE
Mutiple entity error in Kill mobs stage

### ISSUE THREAD

**Issue by Eternirya** [FlyingPikachu/Quests#693]
What is your Quests version / build number: 3.6.2-b654

Describe the problem and how to replicate it.:

new Quest -> new Stage -> Mobs -> Kill mobs -> Set mob types -> "Zombie Skeleton" (and other mobs type) -> can't Done (already set amount and setup npc start, ask msg, finish msg, ...)

Still work when typo "Zombie".

**Comment by FlyingPikachu** [comment]
You must also set the "mob amounts" in the same menu as the "mob types". Most likely the error telling you this went unnoticed because it generates above the prompt (I'll look into changing that soon). This is the error, in red text:

![moberror](https://user-images.githubusercontent.com/2267126/52594274-16050a80-2e19-11e9-8573-17452e897935.png)

So in other words, add the number of mobs to kill by selecting option 2, then you will be able to close the prompt.
