### ISSUE TITLE
Quests Not completing!

### ISSUE THREAD

**Issue by Arcantiz** [FlyingPikachu/Quests#70]
Hey there I'm having a little trouble with the plugin at the minute. The quest does not complete, I will use my quest as an example for this and explain the issue in depth.
Firstly, you talk to the NPC to get the quest and accept it (This Works fine).
Secondly, it asks you to kill pigs at the Farm pens (This Works fine).
Next, Upon killing the pigs it asks you to deliver the pork and then talk to the NPC. This is the problem this is the end of the quest. It does not give the reward and it doesnt say quest completed. It also says that I completed those actions (Delievering Pork and Talking to the NPC) I'm using the latest version of Quests (2.3.4) Using Spigot 1.8 I not sure of the build it must be something like #1649 I think. Please help!

**Comment by FlyingPikachu** [comment]
Please post your quests.yml file.

**Comment by Arcantiz** [comment]
http://pastebin.com/V9ZhNMeA

**Comment by Arcantiz** [comment]
Just to let you know incase this means anything I have the Mythic Mobs and SkillAPI Quest modules

**Comment by Arcantiz** [comment]
Ok, the quest works if I take out the stage 2  which is talk to npcs.

**Comment by Formula350** [comment]
I don't know if it relates any, but I sometimes run across where if we have too many quest objectives, in a single stage usually, that for a random person the quests objectives they have completed do not tally correctly. For example if it asks to turn in 10x Prismarine Shards, 20x Prismarine Crystals, 2x Nether Stars, 6x Ghast Tears, you may turn in the first three and suddenly it will say you've turned in 5 Nether Stars, 32 Pris Shards, and 8 Ghast Tears. The problem that causes is it won't accept the tears the player is trying to turn in as the final item, yet it doesn't count it completed.

Similarly, there has been a time or two where it will be accepting their items and then flat out say they haven't turned any in. Their /quest output will report 0 on them (and is reflected in their data file as well).

Unfortunately I don't have any on-hand instances of a quest that has done that, as usually they have either been edited to remove a certain item or they have been one of our Weekly Quests so are no longer in the yml file.

Not much help, I know :( lol I'll try and keep an eye out for if it does it in 2.3.5 since updating to it a few days ago.
-Form

**Comment by FlyingPikachu** [comment]
I was able to complete the quest (with stage 2), although no rewards are listed:

http://i.imgur.com/vufj0s8.png

This is because you are running a command as the reward. As such, there is no "physical" reward to list.

**Comment by Arcantiz** [comment]
well as soon as I removed the Talk to NPC's in stage 2 it work and listed the rewards

**Comment by FlyingPikachu** [comment]
What rewards would that be? The quest you linked to only had 1 command reward.
