### ISSUE TITLE
CustomObjective didnt save all data and Display of CustomObjective

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#706]
Ver 3.6.4

My CustomObjective: https://pastebin.com/0BpyZ422

1. CustomObjective didnt save all data if i set reward of quest. First time, i didnt set the reward, it saved all data but after i had set reward it only save "Ten hoi thoai"

2. Display of CustomObjective
  Being in quest progress: Nói chuyện với §c [NPC] Mia (Click chuột trái để nói chuyện)
  Finish: Nói chuyện với §c %Ten npc% (Click chuột trái để nói chuyện)
  Placeholder wasnt be replaced when it send finish message.

Thanks for reading. I hope you will fix it soon!

**Comment by FlyingPikachu** [comment]
Your init block looks correct to me, although I would pass `null` rather than `""` for your string prompts. That leads me to believe the issue lies within the rest of your code. Without seeing it, there's no way for me to offer further assistance. Feel free to post your code and I'd be glad to reopen the issue.

**Comment by keodeovn** [comment]
That's all code of my CustomObjective. I have my plugin QuestConversation but it just get data from quest. I realize that when I created quest with only my CustomObjective, it saved all data of this quest. But when I created it with requirement, reward,... it only saved first data of data map. 

Your plugin is wonderful, i love it. Hope you will check it back soon. Thank you!
