### ISSUE TITLE
The most serious mistake in the world!!!

### ISSUE THREAD

**Issue by thetopthailand** [FlyingPikachu/Quests#707]
Is a good plugin But I found many problems, just select the mission and exit the game. After that, the player will connect back to the server. The mission is accomplished without having to complete the mission.

**Comment by FlyingPikachu** [comment]
Thanks for your report. I was not able to replicate the issue.

Regardless, I must close this because you did not follow the issue template. Please answer the following questions in a _new_ issue:

**What is your Quests version / build number (do _not_ say "latest")?**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
