### ISSUE TITLE
Somthing wrong with saving data of  CustomObjective

### ISSUE THREAD

**Issue by keodeovn** [FlyingPikachu/Quests#718]
My first post: https://github.com/FlyingPikachu/Quests/issues/706
More:
That's all code of my CustomObjective. I have my plugin QuestConversation but it just get data from quest. I realize that when I created quest with only my CustomObjective, it saved all data of this quest. But when I created it with requirement, reward,... it only saved first data of data map.

Your plugin is wonderful, i love it. Hope you will check it back soon. Thank you!

**Comment by FlyingPikachu** [comment]
Your code from before: https://pastebin.com/0BpyZ422

Creating a plugin ("QuestConversation") for custom objectives/rewards/requirements rather than a module is neither supported nor recommended, as that is not indicative of this project's goals for the user experience. It is recommended that you release a module along with your plugin so that users may safely break linkage with your plugin at any time. Quests will not populate the datamap properly unless the code is loaded as module from the _plugins/Quests/modules_ folder at startup. When creating a module, you may wish to catch an event as such is the purpose of creating a CustomObjective class which extends Listener.
