### ISSUE TITLE
[Feature Request] Starting Quests With Specific Entities (UUID)

### ISSUE THREAD

**Issue by CraftSteamG** [FlyingPikachu/Quests#722]
**What does your feature do?**
Add the option to start a quest with any entity by either selecting the entity on Quest Creation, or by inputting the entities UUID.

**How would people use it?**
This would make it easier for people who cannot use Citizens, and could provide good ways to start quests.

I do not believe it would require a lot of work code-wise, as you'd just check against the entities UUID, but I could be mistaken.

Otherwise, I've been enjoying this amazing plugin, and thank you!

**Comment by FlyingPikachu** [comment]
Thanks for your interest in Quests! Using non-Citizens entities to start a quest is not planned at this time. The Citizens plugin takes steps to ensure its entities are difficult to destroy by players and/or the server. Normal entities do not have this ability, and so a Zombie that one might use to start a quest could be gone forever in a matter of minutes. Because of this volatility, it just isn't practical for Quests to support that.

Bear in mind that you can change Citizens NPCs to look like other, non-human entities. For example, with an entity selected you can use _/npc type Zombie_ to change the NPC into a Zombie which should never despawn and can still be used to start quests.

**Comment by CraftSteamG** [comment]
Oh well, I can't use Citizens on my server, and this feature is a necessity because of that. I guess I'd have to pay a dev to include it. Sorry for bothering you!
