### ISSUE TITLE
Implement support of minecraft scoreboards in stages

### ISSUE THREAD

**Issue by RedMachete** [FlyingPikachu/Quests#724]
**What does your feature do?**
Add's players to a created scoreboard
**How would people use it?**
An easier way to make custom stages without using denzien. For example, add's people to an objective called "time" where the type is something like stat.timeplayed (not a real thing i think but an example" and to pass the stage, they would have to reach a specified scoreboard value. That way, in the example, we could have quests for just time played, or any other type of scoreboard.

**Comment by FlyingPikachu** [comment]
Thanks for using Quests. My knowledge of the scoreboard system is limited, but it's my understanding that mcMMO uses scoreboards for stats. Since many Quests users also use mcMMO, I'm concerned that the scoreboards might interfere with one another. It's for these reasons I'm going to pass on this suggestion.

You could always request that someone build a module for this at https://www.spigotmc.org/forums/hiring-developers.55/ (not associated with Quests)
