### ISSUE TITLE
Item do not save

### ISSUE THREAD

**Issue by HellaMixel** [FlyingPikachu/Quests#81]
What is your Quests version / build number?
2.9.5-b152

Please describe the problem and how to replicate it. Any console errors?
I'm having two issues one being an item issue.

- I created a quest and I named it 'Help!'. The quest loads fine and I set everything up as I liked. The next thing is that when I try adding the rewards for the quest it does not save. This is only for an item. I tried to manually all the item, and also using '0' to automatically add the item. The item will not save when I save the quest. On the other hand, if I go do it manually it will actually save and work when I go into the config and do /questsadmin reload. I do not know how to add lores and enchantments and all the other configurations you can do in-game, in the config file. It would save me a lot of time being able to do it in-game rather then having to go in the quests.yml file and do it manually each time. Everything else works besides that.

Running: Spigot 1.8.8

Can you provide an example quest from quests.yml _using Pastebin.com_?
 - https://pastebin.com/KVnFESq9
This is the config that I did manually, since it was not working in-game.

**Comment by FlyingPikachu** [comment]
I was able to add a _Thorns I_ Diamond Sword named "Coolest Sword" to your quest using the in-game editor. Here's what that looks like - https://pastebin.com/3Ask9SwH

For more information on this format, please see - https://github.com/FlyingPikachu/Quests/wiki/Item-Formatting

Please note that, if entering it manually, the enchantments menu is picky when it come to names. You likely must enter it as the menu presents ("Thorns" rather than "thorns" or "Thorn"). Afterwards you must enter the level (1, 2, 3, et al.).

For any additional help with the quests.yml, check out - https://github.com/FlyingPikachu/Quests/wiki/Configuration

Thanks for your interest in Quests!
