### ISSUE TITLE
Daily Quests

### ISSUE THREAD

**Issue by seema84** [FlyingPikachu/Quests#82]
why is completed behind a quest, if it has not done that day
that is superfluous, please remove

**Comment by FlyingPikachu** [comment]
I do not understand. Please rephrase.

**Comment by seema84** [comment]
I think that you can handle different - Please look an find a "good" other way.
A differently color does not sound as good.

**Comment by Leescar** [comment]
So the feature being requested is for the 'completed' to vanish once a quest is re-doable?
Is that even possible?

Quests use a kind of 'push pin' system where things are either yes or no.
Has user done quest? yes? pin quest name under completed list and apply a completed tag at quest view
Has user done quest? no? Send quest view as normal.


I cannot even fathom the amount of coding it would take for the system to recognize that a quest has been completed and then for it to display its not completed because that information is tracked for multi teir style quests and quest chains that require them done in a certain order ( certain quests prerequisite to a another)


How would a 'daily' quest even work, its setup to use a redo time, there isn't a clock-check system its a count-down system. 
So the very ideal of a 'daily' is out of the question. 
A quest with a days-24hour- delay is possible sure.


Now looking at this thread has me thinking of another way (Though color changing to me personally sounds lovely, green for repeatable, red for non-repeatable, orange for time remaining in repeat delay, how simple and straightforward is that?! anyways-)
This other way would be to grab the count down of a quests redo delay and prefix that onto a quests name. Lets say the quest 'mine time' has a 2 hour delay it would show [120m] Mine time [Completed]
and a non-repeatable mine time would be [0] Mine time [completed]

Colorization and the number are both really straight forward and simple direct ways of showing a repeatable quest.
 
Though im not too sure how easy or resource hungry a check like that would be.

**Comment by FlyingPikachu** [comment]
Closing as this does not seem to be a widespread issue. Color coding seems to be the method of choice should this be requested again. Thanks for your input!
