### ISSUE TITLE
"quests top" failure caused by non-uuid-converted username

### ISSUE THREAD

**Issue by SXRWahrheit** [FlyingPikachu/Quests#91]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
b169

(__Required__) Please describe the problem and how to replicate it. Any console errors?
/quests top 10

https://hastebin.com/qafuyeficu.vbs

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
N/A but can provide flatfile data if needed

**Comment by FlyingPikachu** [comment]
This appears to be caused by a file in the /data folder that is named after the playername rather than UUID. Seeing as the Quester.saveData() function only saves file names as UUIDs, I'm unsure how this could have come about. Perhaps you ran a very old version of Quests at some point (prior to UUID conversion)?

At any rate, replacing the file name with the player's UUID will resolve the issue. Alternatively, if there a large number of files, setting 'convert-data-on-startup' to 'true' in config.yml and loading the plugin should resolve the problem.

As for a coded fix, I will try/catch this and display a console warning in the next commit.

**Comment by SXRWahrheit** [comment]
Thanks!
