### ISSUE TITLE
finish-message doesn't work in a stage

### ISSUE THREAD

**Issue by EmmanuelVlad** [FlyingPikachu/Quests#95]
Build: 171

finish-message doesn't do anything in the completion of a stage, no errors.

**Comment by FlyingPikachu** [comment]
Just now, I was able to complete the default Stone Miner quest and get the finish-message ("<yellow>Well done. Here is your reward."). I should note that it takes a second to appear in chat, but this is by design.

At this point, you'll have to provide either an error or an example quest from quests.yml for testing.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP. Comment with requested information to re-open. Thanks!

**Comment by EmmanuelVlad** [comment]
Because it was the only stage from the quest, try adding more stages and `finish-message` on each one :)
